### PR TITLE
Use the index of stdin instead of zero

### LINKED ISSUE #671: Sourcemap entry path is 'stdin' with dart-sass
* Operating System: Windows 10
* Node Version: 10.9.0
* NPM Version: 6.2.0
* webpack Version: 4.29.5
* sass-loader Version: 7.1.0

### Expected Behavior
Sourcemap entrypoint is a path to a file.

### Actual Behavior
Sourcemap entrypoint (one of the sources) is "stdin" and that causes loaders in the chain that rely on sourcemaps (resolve-url-loader) to fail.

### Code

```js
  // webpack.config.js
...
                        "css-loader",
                        {
                            loader: 'postcss-loader',
                            options: {
                                plugins: () => [require('autoprefixer')],
                                config: {
                                    path: path.join(__dirname, "./postcss.config.js")   
                                }
                            }
                        },
                        {
                            loader: 'resolve-url-loader',
                            options: {
                                debug: true,
                                sourceMap: true
                            }
                        },
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: true,
                                sourceMapContents: true,
                                sourceMapRoot: "/web/",
                                implementation: require('sass'),
                            }
                        }
...
```

The reason for this issue is that the "stdin" overwrite is harcoded overwriting the first element in the source.map:
```
   result.map.sources[0] = path.relative(process.cwd(), resourcePath);
``` 

However in my test for dart-sass the "stdin" element is at the end of the array!
That also means that one sourcemap source path is wrongly overwritten.
As soon as I changed the loader to:

```
            var index = result.map.sources.indexOf("stdin");
            if(index >= 0) {
                result.map.sources[index] = path.relative(process.cwd(), resourcePath);
            }
```

Everything is fine again!

### How Do We Reproduce?
Use resolve-url-loader together with dart-sass and try to:
```
background-image: url('../test.png');
```

Reason is that resolve-url-loader isn't able to get the path to the containing file from the source maps.

### PR DESCRIPTION
**Pull request by FractalBoy**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Solves issue #671, which breaks the use of resolve-url-loader

### Breaking Changes

None

### Additional Info

This will look for "stdin" in the list of sources and replace it with the Sass file. If it can't find the string for whatever reason, it will ~~fall back to the previous functionality and just use the 0th index~~ not do anything.

fixes #671

### CODE REVIEW

**Comment by FractalBoy** [comment]
I think the test cases actually do cover this, but I can't figure out how to make them break.

stdin is in the 0th position of `result.map.sources` for both dart-sass and node-sass.

**Comment by evilebottnawi** [comment]
@FractalBoy hm, it is very strange, for `sass`(`dart-sass`) `stdin` should be at end, maybe need update `sass` (`dart-sass`) to latest version, anyway good job

**Comment by FractalBoy** [comment]
Upgrading `sass` to 1.20.1 didn't break any tests in master.

File: lib/loader.js [hunk 1]
```diff
@@ -86,7 +86,14 @@ function sassLoader(content) {
...
       // eslint-disable-next-line no-param-reassign
-      result.map.sources[0] = path.relative(process.cwd(), resourcePath);
+      let stdinIndex = result.map.sources.findIndex(
+        (source) => source.indexOf('stdin') !== -1
+      );
+      stdinIndex = stdinIndex !== -1 ? stdinIndex : 0;
+      result.map.sources[stdinIndex] = path.relative(
+        process.cwd(),
+        resourcePath
+      );
```
Comment (evilebottnawi) [inline lib/loader.js]: Ok, thanks for ivnestigation, maybe rewrite this like:
```
if (stdinIndex !== -1) {
  result.map.sources[stdinIndex] = path.relative(
        process.cwd(),
        resourcePath
      );
}
```

This allow to us protect code if stdin was excluded from sources in future

Comment (FractalBoy) [reply lib/loader.js]: I'm not sure I understand the point - the way I've written it, `stdinIndex` will never be -1. If it is, it will be 0.

Comment (evilebottnawi) [reply lib/loader.js]: @FractalBoy I am afraid what in future `node-sass`/`sass` can remove `stdin` from `result.map.sources` so better check `stdin` exists in `sources` and then modify

Comment (evilebottnawi) [reply lib/loader.js]: Now- If `stdin` not exists in `sources` we break source map, because on `0` index will be path to source

Comment (FractalBoy) [reply lib/loader.js]: I see. I'll make the change.

Comment (FractalBoy) [reply lib/loader.js]: Maybe it would actually be better to remove stdin if it exists and then always add the path?
```
      const stdinIndex = result.map.sources.findIndex(
        (source) => source.indexOf('stdin') !== -1
      );

      const relativeResourcePath = path.relative(
        process.cwd(),
        resourcePath
      );

      if (stdinIndex !== -1) {
        result.map.sources[stdinIndex] = relativeResourcePath;
      } else {
        result.map.sources.push(relativeResourcePath);
      }
```

Comment (FractalBoy) [reply lib/loader.js]: Actually, nevermind, that would probably screw up the source maps since it wouldn't line up correctly.

**Comment by FractalBoy** [comment]
@evilebottnawi do you know when your next release will be?

**Comment by evilebottnawi** [comment]
@FractalBoy this or next week

**Comment by FractalBoy** [comment]
@evilebottnawi awesome, thanks

**Comment by FractalBoy** [comment]
@evilebottnawi will you be publishing a new release soon? i need this update for a project i'm working on.

**Comment by FractalBoy** [comment]
@evilebottnawi when will your next release be? it's been over a month since you said it would be released.

**Comment by evilebottnawi** [comment]
@FractalBoy sorry for delay, next week, there are a lot of work
