### PR TITLE
fix: prefer `sass`/`scss`/`css` extensions

### LINKED ISSUE #556: import prefer `js` over `css/sass/scss`
It appears that 7.0 breaks sass modules we are using from npm. I guess it is related to https://github.com/webpack-contrib/sass-loader/pull/479

For example foundation-sites that we are using imports it's internal modules like this:
```
// Sass utilities
@import 'util/util';
```

Now, unfortunately 'util/util' is a valid file inside node_modules (from 'node-util' pkg), and the build fails with errror like this:

```
ERROR in ./src/style.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style.scss)
Module build failed: 
// Copyright Joyent, Inc. and other Node contributors.
^
      Invalid CSS after "...N THE SOFTWARE.": expected 1 selector or at-rule, was "var formatRegExp = "
      in ###/webpack-sass-broken-imports/node_modules/util/util.js (line 1, column 1)
 @ ./src/style.scss 2:14-117
 @ ./src/index.js
```
repro repo: https://github.com/larpo/webpack-sass-broken-module-imports

Is there a way to revert to the old behaviour? I don't see any mentions on READMe about how to configure the aliasing behaviour.

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [x] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fixes #556

### Breaking Changes

Should be no, but if you faced with problem feel free to open new issue

### Additional Info

No

### CODE REVIEW

File: lib/loader.js [hunk 1]
```diff
@@ -37,11 +54,11 @@ function sassLoader(content) {
...
   let resolve = pify(this.resolve);
 
-  // Supported since v4.27.0
-  if (this.getResolve) {
+  // Supported since v4.36.0
+  if (hasGetResolve(self)) {
     resolve = this.getResolve({
-      mainFields: ['sass', 'main'],
-      extensions: ['.scss', '.sass', '.css'],
+      mainFields: ['sass', 'style', '...'],
```
Comment (zackschuster) [inline lib/loader.js]: may i ask what the `'...'` additions mean (here and the line below)?

also, does this change mean i can use the `"style"` field in `package.json`?

**Comment by evilebottnawi** [comment]
> may i ask what the '...' additions mean (here and the line below)?

it extends you default configuration, you can use global `mainFields` https://webpack.js.org/configuration/resolve/#resolvemainfields, to avoid break logic we just extends them

> does this change mean i can use the "style" field in package.json?

yes, you can use `sass` and/or `style` field in `package.json`
